---
name: terraform
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  build_terraform:
    name: Terraform Teste
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        continue-on-error: true

      - name: Output STDOUT
        id: output_stdout
        run: echo ${{ steps.plan.outputs.stdout }}
      
      - name: Output STDERR
        id: output_stderr
        run: echo ${{ steps.plan.outputs.stderr }}

      - name: Output EXITCODE
        id: output_exitcode
        run: echo ${{ steps.plan.outputs.exitcode }}

      - name: Discord Message
        uses: th0th/notify-discord@v0.4.1
        if: ${{ always() }}
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_JOB_NAME: "Build and deploy"
          GITHUB_JOB_STATUS: ${{ job.status }}